#!/usr/bin/env php
<?php
//
// This script is expected to be run from the root of the laravel project
//
require getcwd().'/vendor/autoload.php';

require_once __DIR__.'/src/Updater.php';

$updater = new Updater();

$updater->run();
